### ISSUE TITLE
t/10_new.t fails (another one)

### ISSUE THREAD

**Issue by eserte** [ytnobody/p5-Net-Azure-NotifcationHubs#2]
Maybe a similar issue like https://github.com/ytnobody/p5-Net-Azure-EventHubs/issues/2

CPAN Testers results:
http://matrix.cpantesters.org/?dist=Net-Azure-NotificationHubs%200.02;reports=1#sl=7,1

**Comment by ytnobody** [comment]
Today I fixed this issue and released as 0.03.

Thank you.
